[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo     = 'pix/vim-align'
hook_add = '''
  let g:Align_xstrlen = 3
'''

[[plugins]]
repo = 'Shougo/neocomplete'
if   = 'has("lua")'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'banyan/recognize_charcode.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'tpope/vim-fugitive'

# lang
## perl
[[plugins]]
repo = 'vim-perl/vim-perl'

[[plugins]]
repo = 'motemen/xslate-vim'

[[plugins]]
repo = 'y-uuki/unite-perl-module.vim'

[[plugins]]
repo = 'moznion/vim-cpanfile'

## ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails' 

## html/javascript/css
[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo     = 'othree/javascript-libraries-syntax.vim'
hook_add = '''
  let g:used_javascript_libs = 'backbone,angularjs,angularui'
'''

[[plugins]]
repo = 'mattn/emmet-vim'

## others
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo  = 'motus/pig.vim'
on_ft = 'pig'

[[plugins]]
repo  = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo  = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo  = 'ekalinin/Dockerfile.vim'
on_ft = 'Dockerfile'

# theme
[[plugins]]
repo        = 'altercation/vim-colors-solarized'
script_type = 'colors'
hook_add    = '''
  colorscheme solarized
'''

[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 'colorscheme': 'solarized' }
'''

